project: Cell_Line_ONT
description: >
  Standard directory structure for ONT sequencing analysis of a single cell line or entity.
  Contains raw and processed data, analysis outputs, and final results.

stages:
  - id: analysis
    desc: Active analysis outputs (genome assembly, CNV, variant calling, etc.)
    dirs:
      - path: analysis/assembly/global_assembly/assembly_fasta
        allow: ["*.fasta", "*.fa", "*.fna", "*.gz"]
        notes: Genome-wide assembled FASTA sequences
      - path: analysis/assembly/global_assembly/dot_plot
        allow: ["*.png", "*.jpg", "*.svg", "*.pdf"]
        notes: Dot-plots comparing assemblies to references
      - path: analysis/assembly/local_assembly/assembly_fasta
        allow: ["*.fasta", "*.fa", "*.fna", "*.gz"]
        notes: Local variant-specific assembled FASTA sequences
      - path: analysis/assembly/local_assembly/dot_plot
        allow: ["*.png", "*.jpg", "*.svg", "*.pdf"]
        notes: Dot-plots for local assemblies
      - path: analysis/copyNumber/img
        allow: ["*.png", "*.jpg", "*.svg", "*.pdf"]
        notes: CNV plots for each chromosome
      - path: analysis/logs
        allow: ["*.log", "*.txt"]
        notes: Log files from analysis runs
      - path: analysis/variants
        allow: ["*.vcf", "*.vcf.gz", "*.tsv", "*.bed"]
        notes: Variant call data

  - id: data
    desc: All data files used in the analysis (raw → processed)
    dirs:
      - path: data/align/raw
        allow: ["*.bam", "*.bai", "*.cram", "*.paf"]
        notes: Aligned raw FASTQ
      - path: data/align/trimmed
        allow: ["*.bam", "*.bai", "*.cram", "*.paf"]
        notes: Aligned adapter-trimmed FASTQ
      - path: data/align/trimmed_filtered
        allow: ["*.bam", "*.bai", "*.cram", "*.paf"]
        notes: Aligned trimmed + size-filtered FASTQ
      - path: data/align/trimmed_filtered_corrected
        allow: ["*.bam", "*.bai", "*.cram", "*.paf"]
        notes: Aligned trimmed, filtered, and Herro-corrected FASTQ

      - path: data/fastq/raw
        allow: ["*.fastq", "*.fastq.gz"]
        notes: Raw FASTQ files from ONT
      - path: data/fastq/trimmed
        allow: ["*.fastq", "*.fastq.gz"]
        notes: Adapter-trimmed FASTQ
      - path: data/fastq/trimmed_filtered
        allow: ["*.fastq", "*.fastq.gz"]
        notes: Trimmed and size-filtered FASTQ
      - path: data/fastq/trimmed_filtered_corrected
        allow: ["*.fastq", "*.fastq.gz"]
        notes: Trimmed, filtered, and Herro-corrected FASTQ

      - path: data/logs
        allow: ["*.log", "*.txt"]
        notes: Log files for alignment and QC jobs

      - path: data/qc/raw
        allow: ["*fastqc.html", "*.zip", "*.txt", "*.png"]
        notes: QC outputs for raw FASTQ
      - path: data/qc/trimmed
        allow: ["*fastqc.html", "*.zip", "*.txt", "*.png"]
        notes: QC outputs for trimmed FASTQ
      - path: data/qc/trimmed_filtered
        allow: ["*fastqc.html", "*.zip", "*.txt", "*.png"]
        notes: QC outputs for trimmed + filtered FASTQ
      - path: data/qc/trimmed_filtered_corrected
        allow: ["*fastqc.html", "*.zip", "*.txt", "*.png"]
        notes: QC outputs for trimmed, filtered, and corrected FASTQ

  - id: results
    desc: FINAL output files — static figures and tables for publication or reporting
    dirs:
      - path: results
        allow: ["*.png", "*.jpg", "*.svg", "*.pdf", "*.xlsx", "*.tsv", "*.csv"]
        notes: Final figures, tables, and reports; no active analysis should happen here

flow:
  - data/fastq/raw -> data/fastq/trimmed
  - data/fastq/trimmed -> data/fastq/trimmed_filtered
  - data/fastq/trimmed_filtered -> data/fastq/trimmed_filtered_corrected
  - data/align/raw -> data/align/trimmed
  - data/align/trimmed -> data/align/trimmed_filtered
  - data/align/trimmed_filtered -> data/align/trimmed_filtered_corrected
  - data/qc/raw -> data/qc/trimmed
  - data/qc/trimmed -> data/qc/trimmed_filtered
  - data/qc/trimmed_filtered -> data/qc/trimmed_filtered_corrected

