name: Test Conda Environments

on:
  push:
    paths:
      - 'envs/*.yml'
  pull_request:
    paths:
      - 'envs/*.yml'
  workflow_dispatch:

jobs:
  test-envs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        envfile: []

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find env files
        id: find_envs
        run: |
          echo "envfiles=$(ls envs/*.yml | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Set matrix dynamically
        uses: actions/github-script@v7
        id: set-matrix
        with:
          script: |
            const envfiles = JSON.parse(process.env.envfiles);
            return { matrix: { envfile: envfiles } };
          result-encoding: string
        env:
          envfiles: ${{ steps.find_envs.outputs.envfiles }}

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  create-conda-envs:
    needs: test-envs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.test-envs.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          environment-file: ${{ matrix.envfile }}
          cache-environment: false

      - name: Confirm environment works
        shell: bash -l {0}
        run: |
          echo "Activated environment from ${{ matrix.envfile }}"
          conda list

